In [ ]:
import pandas as pd
data = pd.read_csv("cars_dataset.csv")
print(data)

    Manufacturer    Model  Sales_in_thousands  __year_resale_value  \
0           Audi       A4              43.652               28.007
1           Audi       A6              14.379               33.365
2         Toyota  Corolla              43.443               11.744
3       Mercedes     E300              32.753               19.240
4            BMW       X5              74.025               17.063
..           ...      ...                 ...                  ...
495       Toyota     RAV4              36.619               11.781
496        Honda      Fit              60.271               12.590
497         Ford    Focus              29.829               26.208
498          BMW       M3              46.665               32.639
499       Nissan   Patrol              65.863                9.957

    Vehicle_type  Price_in_thousands  Engine_size  Horsepower  Wheelbase  \
0      Passenger               44.12          3.5          90      120.2
1      Passenger               45.24          3.9         164       97.2
2      Passenger               15.93          4.5         292      117.9
3            SUV               33.20          3.2         202      111.7
4            SUV               32.08          2.5         378      116.0
..           ...                 ...          ...         ...        ...
495    Passenger               15.60          1.8         378      116.5
496          SUV               26.35          2.8         286      120.4
497          SUV               32.97          2.6         139      124.4
498    Passenger               67.30          3.9         163      123.7
499          SUV               18.19          1.6         215      110.2

     Width  Length  Curb_weight
0     73.2   190.0        5.275
1     68.4   194.2        2.554
2     75.6   199.2        4.748
3     74.3   162.8        3.159
4     66.9   165.7        5.377
..     ...     ...          ...
495   66.9   205.7        4.094
496   75.1   164.9        3.214
497   68.2   176.2        3.290
498   71.5   194.5        4.114
499   65.3   164.0        2.970

[500 rows x 12 columns]

In [ ]:
df = pd.DataFrame(data)
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight
0,Audi,A4,43.652,28.007,Passenger,44.12,3.5,90,120.2,73.2,190.0,5.275
1,Audi,A6,14.379,33.365,Passenger,45.24,3.9,164,97.2,68.4,194.2,2.554
2,Toyota,Corolla,43.443,11.744,Passenger,15.93,4.5,292,117.9,75.6,199.2,4.748
3,Mercedes,E300,32.753,19.240,SUV,33.20,3.2,202,111.7,74.3,162.8,3.159
4,BMW,X5,74.025,17.063,SUV,32.08,2.5,378,116.0,66.9,165.7,5.377
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Toyota,RAV4,36.619,11.781,Passenger,15.60,1.8,378,116.5,66.9,205.7,4.094
496,Honda,Fit,60.271,12.590,SUV,26.35,2.8,286,120.4,75.1,164.9,3.214
497,Ford,Focus,29.829,26.208,SUV,32.97,2.6,139,124.4,68.2,176.2,3.290
498,BMW,M3,46.665,32.639,Passenger,67.30,3.9,163,123.7,71.5,194.5,4.114
499,Nissan,Patrol,65.863,9.957,SUV,18.19,1.6,215,110.2,65.3,164.0,2.970

In [ ]:
df['Model']

0           A4
1           A6
2      Corolla
3         E300
4           X5
        ...
495       RAV4
496        Fit
497      Focus
498         M3
499     Patrol
Name: Model, Length: 500, dtype: object

In [ ]:
df['Model'][0]

'A4'

In [ ]:
df['Model'][499]

'Patrol'

In [ ]:
df['Manufacturer'][0]

'Audi'

In [ ]:
df['Wheelbase'][5]

np.float64(116.3)

In [ ]:
df['Horsepower'][8]

np.int64(119)

In [ ]:
df.loc[0:5,['Manufacturer','Vehicle_type']]

  Manufacturer Vehicle_type
0         Audi    Passenger
1         Audi    Passenger
2       Toyota    Passenger
3     Mercedes          SUV
4          BMW          SUV
5          BMW          SUV

In [ ]:
df.iloc[0:5,[0,1,2,3,4]]

  Manufacturer    Model  Sales_in_thousands  __year_resale_value Vehicle_type
0         Audi       A4              43.652               28.007    Passenger
1         Audi       A6              14.379               33.365    Passenger
2       Toyota  Corolla              43.443               11.744    Passenger
3     Mercedes     E300              32.753               19.240          SUV
4          BMW       X5              74.025               17.063          SUV

In [ ]:
df.iloc[:,0]

0          Audi
1          Audi
2        Toyota
3      Mercedes
4           BMW
         ...
495      Toyota
496       Honda
497        Ford
498         BMW
499      Nissan
Name: Manufacturer, Length: 500, dtype: object

In [ ]:
df.iloc[0:499]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight
0,Audi,A4,43.652,28.007,Passenger,44.12,3.5,90,120.2,73.2,190.0,5.275
1,Audi,A6,14.379,33.365,Passenger,45.24,3.9,164,97.2,68.4,194.2,2.554
2,Toyota,Corolla,43.443,11.744,Passenger,15.93,4.5,292,117.9,75.6,199.2,4.748
3,Mercedes,E300,32.753,19.240,SUV,33.20,3.2,202,111.7,74.3,162.8,3.159
4,BMW,X5,74.025,17.063,SUV,32.08,2.5,378,116.0,66.9,165.7,5.377
...,...,...,...,...,...,...,...,...,...,...,...,...
494,Ford,Focus,63.612,38.387,Passenger,54.12,3.5,200,113.6,69.4,197.4,3.846
495,Toyota,RAV4,36.619,11.781,Passenger,15.60,1.8,378,116.5,66.9,205.7,4.094
496,Honda,Fit,60.271,12.590,SUV,26.35,2.8,286,120.4,75.1,164.9,3.214
497,Ford,Focus,29.829,26.208,SUV,32.97,2.6,139,124.4,68.2,176.2,3.290
498,BMW,M3,46.665,32.639,Passenger,67.30,3.9,163,123.7,71.5,194.5,4.114

In [ ]:
df.loc[:,['Manufacturer']]

    Manufacturer
0           Audi
1           Audi
2         Toyota
3       Mercedes
4            BMW
..           ...
495       Toyota
496        Honda
497         Ford
498          BMW
499       Nissan

[500 rows x 1 columns]

In [ ]:
df.Manufacturer == 'Audi'

0       True
1       True
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Manufacturer, Length: 500, dtype: bool

In [ ]:
df.Manufacturer=='BMW'

0      False
1      False
2      False
3      False
4       True
       ...
495    False
496    False
497    False
498     True
499    False
Name: Manufacturer, Length: 500, dtype: bool

In [ ]:
df.loc[(df.Manufacturer=='Audi') & (df.Engine_size==2.1)]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight
113,Audi,A4,44.572,25.339,Passenger,32.77,2.1,251,113.8,72.1,201.8,2.696
194,Audi,A4,47.275,17.940,Passenger,39.34,2.1,379,115.6,72.5,186.2,4.572
409,Audi,Q5,50.354,27.539,Passenger,51.91,2.1,217,112.5,69.5,163.9,3.581
482,Audi,Q5,51.747,23.327,SUV,47.93,2.1,435,99.0,79.4,178.9,5.358
489,Audi,A3,49.841,43.601,Passenger,74.21,2.1,279,120.3,69.4,186.4,2.649

In [ ]:
df.loc[(df.Manufacturer=='Audi') | (df.Engine_size==2.1)]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight
0,Audi,A4,43.652,28.007,Passenger,44.12,3.5,90,120.2,73.2,190.0,5.275
1,Audi,A6,14.379,33.365,Passenger,45.24,3.9,164,97.2,68.4,194.2,2.554
14,Audi,A3,49.449,42.689,SUV,47.73,2.9,99,103.4,69.9,164.3,2.855
22,Chevrolet,Malibu,59.990,27.064,SUV,57.36,2.1,199,98.4,78.8,178.6,3.906
30,Kia,Picanto,25.346,13.446,SUV,26.05,2.1,126,99.4,72.7,184.9,4.929
...,...,...,...,...,...,...,...,...,...,...,...,...
475,Audi,Q7,9.268,32.726,Passenger,40.77,4.9,223,113.1,79.5,188.0,2.824
478,Audi,A6,25.807,17.140,SUV,29.52,4.5,298,120.7,69.9,209.4,3.296
482,Audi,Q5,51.747,23.327,SUV,47.93,2.1,435,99.0,79.4,178.9,5.358
487,Audi,Q5,67.304,42.646,Passenger,62.04,3.3,396,97.4,70.2,178.1,2.229
489,Audi,A3,49.841,43.601,Passenger,74.21,2.1,279,120.3,69.4,186.4,2.649